# GitHub Action for Laravel
# https://github.com/shivammathur/setup-php/blob/master/examples/laravel-mysql.yml
name: tests-laravel-8

on: [push, pull_request]

jobs:
  tests:
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1']
        stability: [prefer-lowest, prefer-stable]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis-phpredis/phpredis@5.3.5, igbinary, msgpack, lzf, zstd, lz4, memcached
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: Set Minimum PHP 8.1 Versions
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require league/commonmark:^2.0.2 phpunit/phpunit:^9.5.8 ramsey/collection:^1.2 brick/math:^0.9.3 --no-interaction --no-update
        if: matrix.php >= 8.1

      - name: Install composer dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Execute tests
        run: |
          mkdir -p build/logs
          vendor/bin/phpunit --testdox --coverage-clover build/logs/clover.xml

      - name: Upload coverage results to coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v
